name: Publish Packages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore "src/Serilog.Sinks.Spectre"
    - name: Build
      run: dotnet build --configuration Release --no-restore "src/Serilog.Sinks.Spectre"
    - name: Publish Serilog.Sinks.Spectre
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
        PROJECT_FILE_PATH: src/Serilog.Sinks.Spectre/Serilog.Sinks.Spectre.csproj
        VERSION_FILE_PATH: src/Serilog.Sinks.Spectre/Serilog.Sinks.Spectre.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        NUGET_SOURCE: https://api.nuget.org
        INCLUDE_SYMBOLS: true